### ISSUE TITLE
Executive.list breaks when faced with multiple positions for one exec

### ISSUE THREAD

**Issue by alexsdutton** [everypolitician/commons-builder#85]
In Northern Ireland, we — rightly or wrongly — pick up two HoG positions, the First Minister and the Deputy First Minister. This leads to `Executive.list` creating a new `Executive` for each and then trying to order them. As the `Executive#executive_item_id` is the same, it tries to order the positions, which are incomparable.

https://github.com/everypolitician/commons-builder/blob/40886d43d4096c2eed4c55a35b0012b478b102e3/lib/commons/builder/executive.rb#L63

Note: It's not enough to just implement `Position#<=>`, as it would still be returning duplicate `Executive`s, when there should be one `Executive` with multiple positions.

**Comment by tmtmtmtm** [comment]
> rightly or wrongly

FWIW: these are very explicitly co-heads of government, under the Good Friday Agreement. The "deputy" First Minister is not a deputy in the traditional sense, but a co-First Minister (which is why Martin McGuinness' resignation brought down the government).

https://en.wikipedia.org/wiki/First_Minister_and_deputy_First_Minister seems quite decent on this, if anyone is particularly interested in the detail.
